#!/usr/bin/env python

"""
script to combine requirements files required for running and
testing the webgnomeapi into one file:

conda_requirements_all.txt

It requires that the other repositories are installed "alongside"
This one.

After running this script, you should be able to make a new
environment with the one command:

conda create -n webgnomeapi --file conda_requirements_all.txt

"""

PYTHON_VER = "3.9"

import datetime
from pathlib import Path
import textwrap

HERE = Path(__file__).parent

req_files = [HERE / "../pygnome/conda_requirements.txt",
             HERE / "../oil_database/adios_db/conda_requirements.txt",
             HERE / "../libgoods/conda_requirements.txt",
             HERE / "conda_requirements.txt",
             HERE / "conda_requirements_test.txt",
             ]

HEADER = f"""        # All WebGnome requirements (including tests)
        #
        # NOTE: This file was auto-generated by:
        #
        # build_requirements_file.py
        #
        # on {str(datetime.date.today())}
        #
        # It should be rerun if any of the requirements have changed
        # for PyGNOME or webgnomeapi

        """

with open("conda_requirements_all.txt", 'wt') as outfile:


    outfile.write(textwrap.dedent(HEADER))

    outfile.write(f"python={PYTHON_VER}\n")

    for req_file in req_files:
        try:
            with open(req_file) as infile:
                print("Adding:", req_file)
                for line in infile:
                    # strip the commented out lines
                    line = line.lstrip()
                    if line and not line[0] == '#':
                        outfile.write(line)
        except FileNotFoundError:
            print("All required repos must be installed alongside this one")
            print("Couldn't open:", req_file)
            raise


